[package]
name = "ln-resource-mgr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.32.6"
rand = "0.9.1"
serde = "1.0.217"
